# Make sure you list all the project template files here in the manifest.
file '404.php'
file 'archive.php'
file 'attachment.php'
file 'author.php'
file 'category.php'
file 'comments.php'
file 'footer.php'
file 'functions.php'
file 'header.php'
file 'index.php'
file 'loop.php'
file 'page.php'
file 'search.php'
file 'sidebar.php'
file 'sidebar-footer.php'
file 'single.php'
file 'tag.php'
file 'screenshot.png'
file '_LICENSE.txt'
file '_READ_ME.txt'
file 'editor-style.css'
stylesheet '_base.scss'
stylesheet 'style.scss', :media => 'screen, projection'
stylesheet '_footer.scss'
stylesheet '_header.scss'
stylesheet '_navigation.scss'
