source 'https://rubygems.org'

# Specify your gem's dependencies in compass-core.gemspec
gemspec

gem 'sass', "~> 3.3.0.rc.2"
gem 'pry'
gem 'diff-lcs', '~> 1.1.2'
gem 'true', "~> 0.2.0.rc.3"
gem 'timecop', "~> 0.5.9.2"
