require "bundler/gem_tasks"
require 'rake/testtask'

require 'bundler/setup'

namespace :test do
  Rake::TestTask.new(:integrations) do |t|
    t.libs << "test/integrations"
    t.libs << "lib"
    t.test_files = FileList['test/integrations/*_test.rb']
    t.verbose = true
  end
end

task :test => ["test:integrations"]

task :default => :test
