base_url: http://compass-style.org

text_extensions: [ 'css', 'erb', 'haml', 'htm', 'html', 'js', 'less', 'markdown', 'md', 'php', 'rb', 'sass', 'scss', 'txt', 'xml' ]

output_dir: output

data_sources:
  -
    type: filesystem_unified
    items_root: /
    layouts_root: /
  -
    type: filesystem_assets
    items_root: /assets
    layouts_root: /assets

watcher:
  dirs_to_watch: ['content', 'layouts', 'lib', 'assets']
  files_to_watch: ['config.yaml', 'Rules']

  notify_on_compilation_success: true
  notify_on_compilation_failure: true
