--- 
data_sources: 
- items_root: /
  layouts_root: /
  type: better_combined
- items_root: /assets
  layouts_root: /assets
  type: filesystem_assets
text_extensions: [ 'css', 'erb', 'haml', 'htm', 'html', 'js', 'less', 'markdown', 'md', 'php', 'rb', 'sass', 'scss', 'txt', 'xml' ]
output_dir: output
base_url: http://compass-style.org
