source :gemcutter

gem 'nanoc3', :git => "git://github.com/chriseppstein/nanoc.git"
gem 'rdiscount'
gem 'thor'
gem 'rack'
gem 'mime-types'
gem 'serve', "1.0.0"
gem 'nokogiri'
gem 'coderay'
gem 'sass', ">= 3.1"
gem 'haml', ">= 3.1"
gem 'rake'
gem 'compass', :path => ".."
gem 'compass-susy-plugin', ">=0.7.0.pre8"
gem 'css-slideshow', "0.2.0"
gem 'json'
gem 'css_parser', "1.0.1"
gem 'ruby-prof'
gem 'rb-fsevent'
gem 'builder'


