source :gemcutter

gem 'nanoc', :git => 'https://github.com/ddfreyne/nanoc.git'
gem 'i18n'
gem 'adsf'
gem 'thin'
gem 'foreman'
gem 'rdiscount'
gem 'thor'
gem 'rack'
gem 'mime-types'
gem 'nokogiri'
gem 'coderay'
gem 'haml'
gem 'rake'
gem 'activesupport', '~> 3.0.10', :require => 'active_support/inflector'
gem 'compass', :path => ".."
gem 'compass-theme', :git => 'git://github.com/Compass/compass-theme.git'
# gem 'compass-susy-plugin', ">=0.7.0.pre8"
# gem 'css-slideshow', "0.2.0"
gem 'json'
gem 'css_parser', "1.0.1"
gem 'ruby-prof'
gem 'rb-fsevent'
gem 'builder'
