source :gemcutter

gem 'nanoc3', :require => false
gem 'rdiscount'
gem 'thor'
gem 'rack'
gem 'mime-types'
gem 'fssm'
gem 'serve'
gem 'nokogiri'
gem 'coderay'
gem 'haml-edge', :require => 'sass'
gem 'rake'