require 'rubygems'
require 'rubygems/package_task'
require 'rake/testtask'
require 'fileutils'

begin 
  require 'rake/dsl_definition'
rescue LoadError
  #pass
end


task :default => [:test]

task :test => [:integrations, :units]

Rake::TestTask.new :units do |t|
  t.libs << 'lib'
  t.libs << 'test'
  test_files = FileList['test/units/**/*_test.rb']
  test_files.exclude('test/rails/*', 'test/haml/*')
  t.test_files = test_files
  t.verbose = true
end

Rake::TestTask.new :integrations do |t|
  t.libs << 'lib'
  t.libs << 'test'
  test_files = FileList['test/integrations/**/*_test.rb']
  test_files.exclude('test/rails/*', 'test/haml/*')
  t.test_files = test_files
  t.verbose = true
end
